#!/usr/bin/env python3

import os
import sys

_BASE = os.path.dirname(os.path.abspath(__file__))
if _BASE not in sys.path:
    sys.path.insert(0, _BASE)

from lib.cli import main

if __name__ == "__main__":
    main()
